# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/9269dc5d-64b8-492c-a018-c6ba228c9694";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/A664-1CC0";
      fsType = "vfat";
    };

    "/mnt/windows" = {
      device = "/dev/nvme0n1p3";
      fsType = "ntfs";
    };
  };

  swapDevices = [ ];

  zramSwap = {
    enable = true;
    algorithm = "zstd";
  };

  nix.maxJobs = lib.mkDefault 8;

  hardware.opengl = {
    enable = true;
    driSupport32Bit = true;
    package = (pkgs.mesa.override {
      galliumDrivers = [ "nouveau" "virgl" "swrast" "iris" ];
    }).drivers;
    extraPackages = with pkgs; [
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      intel-media-driver
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [ libva ];
  };

  services.fstrim.enable = true;

  services.tlp = {
    enable = true;
    extraConfig = ''
      CPU_SCALING_GOVERNOR_ON_AC=performance
      CPU_SCALING_GOVERNOR_ON_BAT=powersave

      CPU_BOOST_ON_AC=1
      CPU_BOOST_ON_BAT=1

      CPU_MIN_PERF_ON_AC=0
      CPU_MAX_PERF_ON_AC=100
      CPU_MIN_PERF_ON_BAT=0
      CPU_MAX_PERF_ON_BAT=100

      CPU_SCALING_MIN_FREQ_ON_AC=0
      CPU_SCALING_MAX_FREQ_ON_AC=3900000
      CPU_SCALING_MIN_FREQ_ON_BAT=0
      CPU_SCALING_MAX_FREQ_ON_BAT=3900000
      
    '';
  };

  hardware.bluetooth = {
    enable = true;
    extraConfig = ''
      [General]
      Enable=Source,Sink,Media,Socket
    '';
  };
  services.blueman.enable = true;
}
