[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "backlight"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
chip = "coretemp-isa-0000"
[block.format]
full = " $icon $max "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "

[[block]]
block = "net"
format = " $icon $ip "

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
[block.format]
full = " $icon  $percentage $time "

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %F %T') "
short = " $icon $timestamp.datetime(f:%R) "

